/**
 * ReliantAI client-site design quality standards.
 *
 * Every template, component, and generation prompt MUST comply with these rules.
 * Goal: senior designer / Awwwards-level craft — never generic AI-generated output.
 */

/** Motion easing used across all templates — NOT ease-in-out / transition-all */
export const PREMIUM_EASE = [0.22, 1, 0.36, 1] as const;

export const MOTION = {
  duration: { fast: 0.2, base: 0.45, slow: 0.7 },
  ease: PREMIUM_EASE,
} as const;

/** Border-radius hierarchy — intentional variation, never uniform 16px everywhere */
export const RADIUS = {
  button: "rounded-md", // 6px
  card: "rounded-lg", // 8px
  panel: "rounded-xl", // 12px — sparingly
  pill: "rounded-full",
} as const;

/**
 * Patterns that signal low-effort / AI-generated sites.
 * NEVER use in templates, prompts, or agent output.
 */
export const BANNED_AI_PATTERNS = [
  "Inter, Geist, system-ui, or default Tailwind sans as display type",
  "Indigo-500 (#6366f1) or generic blue-500 (#3b82f6) as primary brand color",
  "Multi-stop gradients (from-X via-Y to-Z) on heroes or sections",
  "Purple-to-blue or blue-to-violet hero gradients",
  "Centered full-viewport hero with vague headline ('Build the future', 'Elevate your X')",
  "Three equal feature cards in a symmetric 3-column grid with identical height/padding/radius",
  "backdrop-blur on navbars, cards, or overlays (glassmorphism cliché)",
  "animate-ping dots or pulsing status indicators",
  "Concentric circle / orb decorations with no semantic content",
  "blur-3xl glow blobs as the only visual interest",
  "transition-all duration-300 ease-in-out on every interactive element",
  "Uniform rounded-xl (16px) on buttons, cards, and inputs",
  "shadow-lg on every card and button",
  "Word-by-word headline reveal animation (overused AI motion)",
  "min-h-screen (100vh) hero — use min-h-[85vh] with asymmetric layout instead",
  "Stock-photo placeholders or generic AI imagery",
  "Vague trust badges without specifics ('Quality Service', 'Expert Team')",
  "FAQ as the default fifth section with generic questions",
  "Emoji in professional copy or outreach SMS",
  "Exclamation-heavy marketing copy ('Amazing!', 'Best in town!')",
] as const;

/**
 * Awwwards / senior-designer quality bar.
 * Every template MUST demonstrate at least 5 of these.
 */
export const AWWWARDS_REQUIREMENTS = [
  "Distinctive typography pairing: serif or editorial display + humanist sans body",
  "Asymmetric layout: grid-cols-[2fr_3fr] or [3fr_5fr], off-center hero composition",
  "Solid section backgrounds with at most ONE subtle radial accent — no multi-stop gradients",
  "Intentional border-radius variation (buttons ≠ cards ≠ panels)",
  "Purposeful motion: state-change easing with cubic-bezier(0.22, 1, 0.36, 1) — not generic fade-in on everything",
  "Editorial typography: tight display tracking, generous body line-height (1.6–1.75)",
  "Real specificity in copy: city names, years in business, license types, review themes",
  "Visual hierarchy through size/weight contrast — not color alone",
  "One signature layout moment per template (offset card, split hero, masonry reviews, etc.)",
  "Restrained color palette: 1 primary + 1 accent + neutrals — no rainbow gradients",
] as const;

/** Shared prompt block prepended to every template generation prompt */
export const DESIGN_QUALITY_PROMPT_BLOCK = `
## MANDATORY: Anti-AI-Slop Design Standards (Awwwards / Senior Designer Bar)

You are building a site that must look hand-crafted by a senior designer at a top agency — NOT generated by AI.

### NEVER include (instant rejection):
${BANNED_AI_PATTERNS.map((p) => `- ${p}`).join("\n")}

### ALWAYS include:
${AWWWARDS_REQUIREMENTS.map((p) => `- ${p}`).join("\n")}

### Typography
- Display: Instrument Serif (editorial, tight tracking on headlines)
- Body: DM Sans (humanist, readable at 16–18px, line-height 1.65)
- NO Inter, Geist, Outfit, or system-ui for display type

### Layout
- Hero: asymmetric 2-column (grid-cols-1 lg:grid-cols-[2fr_3fr]), left-aligned copy, min-h-[85vh]
- Services: vary card sizes — one featured (span-2 or taller), rest secondary — NOT three identical cards
- Section rhythm: alternate density (tight stats bar → spacious about → tight FAQ)

### Color
- Use the template's trade-specific palette ONLY — never default Tailwind indigo/blue-500
- Backgrounds: solid slate-950 / white / stone-50 — single radial accent at 4–8% opacity max
- CTAs: solid fill, subtle hover darken — no colored shadow-lg glow

### Motion
- Easing: cubic-bezier(0.22, 1, 0.36, 1) for all transitions
- Animate opacity + transform only — never transition-all
- Max 2 animated elements per viewport on load — restraint signals craft

### Copy (if generating text)
- Headlines: specific + local ("Austin's 15-Year HVAC Team" not "Your Comfort Experts")
- Subheads: one concrete benefit with a number or timeframe
- Trust bar: license numbers, certifications, response times — not adjectives
`.trim();
